[package]
name = "U256"
version = "0.3.9"
upgrade_policy = "immutable"

[addresses]
u256 = "0x43417434fd869edee76cca2a4d2301e528a1551b1d719b75c350c3c97d15b8b9"

[dev-dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/move-stdlib"
addr_subst = { std = "0x1" }
